- .travis.yml
- city-infrastructure-platform/settings.py
- city-infrastructure-platform/urls.py
- tests/test_dummy.py
Previously travis build was broken
no refs
> Update travis configuration

- Dockerfile
- README.md
- docker-compose.yml
- docker-entrypoint.sh
- uwsgi_docker.ini
Add possibility to run project with Docker as a service.
Add possibility to run project with Docker Compose (service and PostGIS-database).
> Dockerize project. Update README.

- city-infrastructure-platform/settings.py
- requirements-dev.txt
- requirements.txt
- setup.cfg
- traffic_control/filters.py
- traffic_control/tests/factories.py
- traffic_control/tests/test_base_api.py
- traffic_control/tests/test_traffic_sign_api.py
- traffic_control/views.py
- Add location filtering to traffic sign plans.
- Create general view set
- Add permission class to limit API visibility
- Add possibility to order results by all fields.
Refs LIIK-40
> Traffic sign plan location filtering

- city-infrastructure-platform/settings.py
- requirements-dev.txt
- requirements.txt
- setup.cfg
- traffic_control/admin.py
- traffic_control/models/barrier.py
- traffic_control/models/common.py
- traffic_control/models/mount.py
- traffic_control/models/road_marking.py
- traffic_control/models/signpost.py
- traffic_control/models/traffic_light.py
- traffic_control/models/traffic_sign.py
- Add django-auditlog
- Register models to auditlog
- Redirect object history page to auditlog history
Refs: LIIK-52
> Revision history for datamodels

- traffic_control/filters.py
- traffic_control/views.py
> Add filters for portal types and traffic sign codes

- city-infrastructure-platform/settings.py
- deployment/apps.py
- deployment/middleware.py
- deployment/test_middleware.py
> Add health check middleware

- traffic_control/utils/send_traffic_sign_reals.py
Auto-generate mount type finnish name content from mount type data during the Traffic Sign Real import.
Simplify existing dict retrieval code.
Refs: LIIK-64
> Auto-generate mount type finnish name

- Dockerfile
Update Dockerfile to use `appuser` user to run the service.
Finetune default ENV-parameters more suitable for development and production.
Cleanup Dockerfile.
Refs #LIIK-76
> Update Dockerfile to use non-root user

- Dockerfile
- docker-entrypoint.sh
Compile Django translations during container startup.
Refs #LIIK-74
> Update Docker translations

- traffic_control/admin.py
- traffic_control/models/traffic_sign.py
- Add requested fields as searchable
- Few fields through relation
- Add lifecycle to list filter, because it is enum and searching that
is more complicated.
Refs LIIK-61
> Add search for TrafficSignReal in Admin page

- traffic_control/management/commands/generate_mount_real_objects.py
> Fix minor typo

- traffic_control/admin.py
- traffic_control/locale/fi/LC_MESSAGES/django.po
- traffic_control/models/traffic_sign.py
- traffic_control/tests/models/test_traffic_sign.py
- traffic_control/tests/test_admin.py
> Show has_additional_sign in TrafficSignReal admin

- city-infrastructure-platform/settings.py
- requirements.txt
- setup.cfg
**Merge after Azure environment is confirmed to be configured properly by Ville Koivunen**
- Add django-storages package with Azure
- Add required variables to settings.py
- Configure default backend to Azure, when doing Azure deployment
Refs LIIK-65
> Configure Azure bucket as a file storage

- traffic_control/tests/test_base_api.py
- traffic_control/tests/test_base_api_3d.py
- traffic_control/views.py
Protect REST-endpoints with role-based permissions.
Update tests.
Refs #LIIK-31
> Role-based access control

- city-infrastructure-platform/locale/fi/LC_MESSAGES/django.po
- city-infrastructure-platform/settings.py
- city-infrastructure-platform/urls.py
- requirements.txt
- setup.cfg
- traffic_control/locale/fi/LC_MESSAGES/django.po
- traffic_control/views.py
Update Swagger documentation with following topics:
- Utilize schema validation
- Simplify versioning
- Add general info related to the overall API-usage
- Add geometry filter usage information
- Add brief descriptions for each entity
Also reorganize urlpatterns so that only Admin UI goes under i18n.
Refs #LIIK-68
> Update Swagger documentation

- traffic_control/schema.py
- traffic_control/serializers.py
- traffic_control/tests/test_api_file_upload.py
- traffic_control/views/_common.py
- traffic_control/views/barrier.py
- traffic_control/views/mount.py
- traffic_control/views/road_marking.py
- traffic_control/views/signpost.py
- traffic_control/views/traffic_light.py
- traffic_control/views/traffic_sign.py
Allow multiple files be uploaded at once for all "real" and "plan" models.
Refs LIIK-111
> Allow multiple files to be uploaded at once

- traffic_control/serializers.py
> Hide mount_type field from traffic sign, signpost and traffic light models

- traffic_control/management/commands/import_traffic_signs_vaisala.py
- traffic_control/tests/management/commands/test_import_traffic_signs_vaisala.py
All Additional traffic signs have a code value starts with "8"
Refs: LIIK-156
> Import additional trafic signs to AdditionalSignReal

- city-infrastructure-platform/settings.py
would not by synched and UID would be in wrong format
> Import SOCIAL_AUTH_PIPELINE from helusers, fixing AD groups synching with login

- traffic_control/management/commands/link_additional_traffic_signs.py
Restore TrafficSign - AdditionalSign FK-linking based on radius.
Refs LIIK-160
> Restore TrafficSign - AdditionalSign FK-linking

- traffic_control/management/commands/generate_mount_real_objects.py
Generate MountReals also for standalone AdditionalSigns.
Refs LIIK-161
> Generate MountReals for standalone AdditionalSigns

- README.md
- requirements-dev.txt
- requirements-prod.txt
- requirements.txt
- setup.cfg
Use bumpversion to manage semantic versioning in the application.
Update RSA-package version to latest.
Also update README with project status indicators and information:
- Build status
- Code coverage
- Requirements
- Code style
Refs LIIK-139
> Add bumpversion configuration

- docker-compose.yml
- traffic_control/models/additional_sign.py
- traffic_control/models/common.py
- traffic_control/serializers.py
- traffic_control/tests/models/test_traffic_control_device_type.py
Limit device_type choices to TrafficControlDeviceType instances to
instances that have target_model set to AdditionalSign
Refs LIIK-163
> Limit AdditionalSignContent device_type choices

- CHANGELOG.md
- traffic_control/admin/traffic_sign.py
> Add a TrafficSignTypeListFilter to TrafficControlDeviceTypeAdmin

- city-infrastructure-platform/settings.py
- map/static/map/app.js
- map/templates/map/map_view.html
- map/views.py
> Make overlay layer source url configurable via a setting variable

- CHANGELOG.md
- docker-compose.yml
- uwsgi_docker.ini
We need this in order to move our services under api.hel.fi-domain.
Refs #LIIK-169
> Change application root URL to "/city-infra"

- city-infrastructure-platform/settings.py
Allow STATIC_URL and MEDIA_URL to be configurable through env-variables
> Update static and media to be configurable

- .dockerignore
- Dockerfile
- docker-entrypoint.sh
Including the map-view build in entry point slows down the dev server startup quite a bit.
Refs: LIIK-180
> Move map-view build to Dockerfile

- map-view/yarn.lock
> Upgrade map-view dependencies

- traffic_control/forms.py
> Add initial value for z coordinate

- traffic_control/admin/additional_sign.py
- traffic_control/admin/barrier.py
- traffic_control/admin/mount.py
- traffic_control/admin/operational_area.py
- traffic_control/admin/plan.py
- traffic_control/admin/road_marking.py
- traffic_control/admin/signpost.py
- traffic_control/admin/traffic_light.py
- traffic_control/admin/traffic_sign.py
> Add source_name and source_id fields to traffic_control model admins

- CHANGELOG.md
- traffic_control/filters.py
Update changelog.
Refs #LIIK-191
> Add traffic control device types filtering by target model

- CHANGELOG.md
> Update README.md for ParkingArea model and ParkingArea importer

- traffic_control/serializers/plan.py
> Mark linked_objects not required in Plan REST API endpoint

- CHANGELOG.md
- map-view/src/App.tsx
- map-view/src/common/Map.ts
- map-view/src/components/FeatureInfo.test.tsx
- map-view/src/components/FeatureInfo.tsx
- map-view/src/components/LayerSwitcher.tsx
- map-view/src/models.ts
This PR introduces several improvements to the feature info window including:
- Display txt, code along with id from feature attributes in feature info window
- Use id from attributes to construct the link to open feature admin editing view
- Query all visible layers for feature info
Refs: LIIK-202
> Improve feature info window

- map-view/package.json
- map-view/yarn.lock
> Resolve node package vulnerabilities

- CHANGELOG.md
- traffic_control/admin/__init__.py
- traffic_control/admin/affect_area.py
> Add ParkingAreaCategory and ParkingArea to django admin

- CHANGELOG.md
- traffic_control/admin/additional_sign.py
- traffic_control/forms.py
> Enable icon widget for AdditionalContent admin inlines

- CHANGELOG.md
- traffic_control/management/commands/import_traffic_sign_reals_blom_kartta.py
- traffic_control/tests/management/commands/test_import_traffic_sign_reals_blom_kartta.py
> Extract numeric values from text when importing blom kartta traffic signs

- traffic_control/management/commands/import_traffic_sign_reals_blom_kartta.py
> Minor flake8 fix

- city-infrastructure-platform/urls.py
- requirements.txt
- setup.cfg
- traffic_control/filters.py
- traffic_control/serializers/additional_sign.py
- traffic_control/serializers/barrier.py
- traffic_control/serializers/mount.py
- traffic_control/serializers/opration_type.py
- traffic_control/serializers/road_marking.py
- traffic_control/serializers/signpost.py
- traffic_control/serializers/traffic_light.py
- traffic_control/serializers/traffic_sign.py
- traffic_control/tests/test_additional_sign_real_api.py
- traffic_control/tests/test_barrier_api.py
- traffic_control/tests/test_mount_api.py
- traffic_control/tests/test_operation_type_api.py
- traffic_control/tests/test_road_marking_api.py
- traffic_control/tests/test_signpost_api.py
- traffic_control/tests/test_traffic_light_api.py
- traffic_control/tests/test_traffic_sign_api.py
- traffic_control/views/_common.py
- traffic_control/views/additional_sign.py
- traffic_control/views/barrier.py
- traffic_control/views/mount.py
- traffic_control/views/operation_type.py
- traffic_control/views/road_marking.py
- traffic_control/views/signpost.py
- traffic_control/views/traffic_light.py
- traffic_control/views/traffic_sign.py
> Device Operations REST endpoints

- city_furniture/templates/wfs/feature_field.html
- city_furniture/templates/wfs/feature_type.html
- city_furniture/templates/wfs/index.html
- city_furniture/views/wfs.py
Add field descriptions to WFS index page.
refs. LIIK-295
> WFS Documentation

- city_furniture/views/wfs.py
- map-view/src/App.tsx
- map-view/src/common/Map.ts
- map-view/src/common/functions.ts
- map-view/src/components/FeatureInfo.test.tsx
- map-view/src/components/FeatureInfo.tsx
- map-view/src/components/LayerSwitcher.test.tsx
- map-view/src/components/LayerSwitcher.tsx
- map-view/src/models.ts
- map-view/yarn.lock
- When clicking a Real device, draw it's plan and a line between then
- Show distance from Real to Plan device in meters
- Setting to toggle displaying Plan on map when Real is clicked
- Allow filtering devices by their Project ID
refs. LIIK-266, LIIK-261
> Map view improvements

- Dockerfile
- city-infrastructure-platform/settings.py
- openshift_client_ip/apps.py
- openshift_client_ip/middleware.py
- openshift_client_ip/test_middleware.py
Add a couple of changes required for building and running Cityinfra in OpenShift
> Run master in openshift

- city_furniture/admin/common.py
- city_furniture/admin/furniture_signpost.py
- city_furniture/models/__init__.py
- city_furniture/models/common.py
- city_furniture/resources/common.py
- city_furniture/resources/furniture_signpost.py
- city_furniture/static/city_furniture/action_formats.js
- city_furniture/tests/test_furniture_signpost_import_export.py
This allows exporting a Furniture Signpost Plan in a ready made template that can be imported as Reals
refs LIIK-306, LIIK-293
> Allow selecting used export resource, resource fixes

- Dockerfile
This makes build more resilient
> Retry downloading Poetry installation script in case of network failure

- .dockerignore
- Dockerfile
- map-view/package.json
- map-view/src/components/FeatureInfo.test.tsx
- map-view/yarn.lock
Update dependencies and refactor Dockerfile a bit.
Refs LIIK-317
> Update NodeJS to v16 and update react-scripts to 5

- city_furniture/admin/furniture_signpost.py
- traffic_control/admin/additional_sign.py
- traffic_control/admin/barrier.py
- traffic_control/admin/mount.py
- traffic_control/admin/road_marking.py
- traffic_control/admin/signpost.py
- traffic_control/admin/traffic_light.py
- traffic_control/admin/traffic_sign.py
- traffic_control/admin/utils.py
- traffic_control/templates/admin/comparison/change_form.html
- traffic_control/templates/admin/comparison/includes/fieldset.html
- traffic_control/templatetags.py
In admin, show Real highlight fields that have different values from the Plan's values
refs. LIIK-305
> Device compare

- uwsgi_docker.ini
> Configure uWSGI workers to enable concurrent queries

- traffic_control/admin/additional_sign.py
- traffic_control/admin/barrier.py
- traffic_control/admin/mount.py
- traffic_control/admin/road_marking.py
- traffic_control/admin/signpost.py
- traffic_control/admin/traffic_light.py
- traffic_control/admin/traffic_sign.py
> Add import/export admin actions for traffic control models

- .github/workflows/python-app.yml
- poetry.lock
- pyproject.toml
Dockerfile already had Python 3.8 in use.
> Use Python 3.8

- docker-compose.yml
Default IP is 0.0.0.0 which can be security risk.
> Bind Docker Compose containers to localhost

- traffic_control/resources/additional_sign.py
- traffic_control/tests/import_export/test_additional_sign_import_export.py
Missing `device_type__code` and `id` columns caused error in runtime.
Refs LIIK-438
> Fix additional sign import with missing columns

- traffic_control/serializers/common.py
> Include `legacy_code` and `legacy_description` in device type REST API response

- city-infrastructure-platform/openapi.md
> Mention the used coordinate reference system in OpenAPI document

- users/admin.py
> Highlight inactive non-deactivated users in admin list view

- city-infrastructure-platform/urls.py
- traffic_control/static/traffic_control/css/catalog.css
- traffic_control/templates/catalogs/additional_sign_catalog.html
- traffic_control/templates/catalogs/traffic_sign_catalog.html
- traffic_control/views/device_catalog.py
The catalog documents are public and are meant to help API users, for example.
Refs LIIK-475
> Add traffic sign and additional sign catalogs

- .github/workflows/python-app.yml
- map-view/package.json
- map-view/public/index.html
- map-view/src/App.test.tsx
- map-view/src/api/__mocks__/MapConfigAPI.ts
- map-view/src/components/FeatureInfo.test.tsx
- map-view/src/components/LayerSwitcher.test.tsx
- map-view/tsconfig.json
- Fix tests in `map-view`
- Run NodeJS tests on CI
> Run NodeJS tests in CI

- map-view/yarn.lock
Squash Dependabot issues to one commit
> Bump NodeJS module versions

- city_furniture/views/furniture_signpost.py
- traffic_control/admin/additional_sign.py
- traffic_control/admin/barrier.py
- traffic_control/admin/mount.py
- traffic_control/admin/road_marking.py
- traffic_control/admin/signpost.py
- traffic_control/admin/traffic_sign.py
- traffic_control/forms.py
- traffic_control/models/responsible_entity.py
- traffic_control/views/additional_sign.py
- traffic_control/views/barrier.py
- traffic_control/views/mount.py
- traffic_control/views/plan.py
- traffic_control/views/road_marking.py
- traffic_control/views/signpost.py
- traffic_control/views/traffic_light.py
- traffic_control/views/traffic_sign.py
Speed up some slow views by optimizing their querysets with  `select_related` and `prefetch_related`.
Refs LIIK-536
> Optimize database queries

- .github/workflows/python-app.yml
- city-infrastructure-platform/templates/admin/base.html
- city-infrastructure-platform/templates/admin/my_account.html
- city-infrastructure-platform/urls.py
- city_infra_instructions/locale/fi/LC_MESSAGES/django.po
- city_infra_instructions/templates/city_infra_instructions/index.html
- city_infra_instructions/templates/city_infra_instructions/instructions/exporter.html
- city_infra_instructions/templates/city_infra_instructions/instructions/general.html
- city_infra_instructions/templates/city_infra_instructions/instructions/importer.html
- city_infra_instructions/templates/city_infra_instructions/instructions_index.html
- locale/fi/LC_MESSAGES/django.po
- map/templates/index.html
- poetry.lock
- pyproject.toml
- traffic_control/static/traffic_control/css/embed.css
- traffic_control/templates/admin/comparison/change_form.html
- traffic_control/templates/admin/comparison/includes/fieldset.html
- traffic_control/templates/admin/import_export/change_list_export_empty.html
- traffic_control/templates/admin/import_export/change_list_import.html
- traffic_control/templates/admin/traffic_control/plan/change_form.html
- traffic_control/templates/admin/traffic_control/plan/plan_relations.html
- traffic_control/templates/admin/traffic_control/widgets/clearable_file_input.html
- traffic_control/templates/admin/traffic_control/widgets/structured_content_widget.html
- traffic_control/templates/admin/traffic_control/widgets/traffic_sign_icon_select.html
- traffic_control/templates/catalogs/additional_sign_catalog.html
- traffic_control/templates/catalogs/traffic_sign_catalog.html
- traffic_control/templates/embed/traffic_sign.html
- traffic_control/tests/factories.py
- traffic_control/tests/test_embed.py
- traffic_control/views/embed.py
The view holds information about the traffic sign and its related additional signs and mount. It is intended to embedded to a sidebar of an external map view.
Refs LIIK-532
> Add embedded view for traffic signs

- .editorconfig
- .github/workflows/python-app.yml
- azure-pipelines-devtest.yml
- azure-pipelines-stageprod.yml
- docker-compose.yml
- Update SonarCloud GitHub action to v2
- Indent YAML files with 2 spaces
- Format YAML files accordingly
> Update SonarCloud GitHub action to v2

- city-infrastructure-platform/tests/test_views.py
- city-infrastructure-platform/views.py
> Show version info in health check view

- traffic_control/admin/traffic_sign.py
- traffic_control/resources/common.py
- traffic_control/resources/device_type.py
- traffic_control/tests/factories.py
- traffic_control/tests/import_export/test_device_type_import_export.py
Refs: LIIK-554
- Support importing and exporting traffic control device types 
- Separate enum field resource matcher to its own mixin class
> Support importing and exporting traffic control device types 

- traffic_control/admin/common.py
- traffic_control/admin/utils.py
> Allow only viewing of replaced and replaces fields in admin-ui

- cityinfra/settings.py
- poetry.lock
- pyproject.toml
> Update django-heluses to 0.10.0

- city_furniture/views/wfs/furniture_signpost.py
- traffic_control/views/wfs/additional_sign.py
- traffic_control/views/wfs/traffic_sign.py
- traffic_control/views/wfs/utils.py
* This is just a workaround, real fix needs to be done to gisserver
* https://github.com/Amsterdam/django-gisserver
Refs: LIIK-589
> fix: GetCapabilities WFS was broken

- traffic_control/admin/plan.py
> feat: Add id field to Plan admin list and detail pages

- city_furniture/serializers/furniture_signpost.py
- city_furniture/tests/test_furniture_signpost_api.py
- city_furniture/views/furniture_signpost.py
- traffic_control/serializers/additional_sign.py
- traffic_control/serializers/barrier.py
- traffic_control/serializers/mount.py
- traffic_control/serializers/road_marking.py
- traffic_control/serializers/signpost.py
- traffic_control/serializers/traffic_light.py
- traffic_control/serializers/traffic_sign.py
- traffic_control/tests/test_additional_sign_real_api.py
- traffic_control/tests/test_barrier_api.py
- traffic_control/tests/test_mount_api.py
- traffic_control/tests/test_road_marking_api.py
- traffic_control/tests/test_signpost_api.py
- traffic_control/tests/test_traffic_light_api.py
- traffic_control/tests/test_traffic_sign_api.py
- traffic_control/views/additional_sign.py
- traffic_control/views/barrier.py
- traffic_control/views/mount.py
- traffic_control/views/road_marking.py
- traffic_control/views/signpost.py
- traffic_control/views/traffic_light.py
- traffic_control/views/traffic_sign.py
> feat: add plan_decision_id to all real apis

- traffic_control/models/utils.py
- traffic_control/tests/test_admin.py
> fix: AuditLog entries for soft delete admin action

- uwsgi/docker.ini
> chore: update uwsgi memory and worker restart config

- traffic_control/mixins/admin.py
- traffic_control/tests/test_admin.py
> feat: Remove cancelling of a soft deleted object

- cityinfra/settings.py
> chore: Change import export's export permission to view instead of add

- cityinfra/settings.py
> chore: require password lenght to be atleast 12

- Dockerfile
> Use AWS ECR docker image repository

- traffic_control/tests/test_api_file_upload.py
- traffic_control/views/_common.py
> fix: check that delete target file belongs to the base object

- .github/workflows/python-app.yml
- check-open-api-schema.sh
- cityinfra/settings.py
- generate-openapi-schema.sh
- traffic_control/schema.py
- traffic_control/serializers/common.py
- traffic_control/static/traffic_control/openapi/openapi.yaml
- traffic_control/views/additional_sign.py
> chore: add openapi schema generation and validation to github actions

- .github/workflows/python-app.yml
- Dockerfile
> chore: update node version to 20 from 16

- locale/sv/LC_MESSAGES/django.po
> chore: Add new swedish translations

- traffic_control/admin/plan.py
> fix: Add decision_date to PlanAdmin

- .github/workflows/release-please.yml
> fix: use master branch instead of main

- cityinfra/settings.py
> fix: Set more strict cookie policies

- cityinfra/settings.py
- traffic_control/forms.py
- traffic_control/resources/common.py
- traffic_control/services/virus_scan.py
- traffic_control/tests/test_api_file_upload.py
- traffic_control/utils.py
- traffic_control/views/_common.py
> feat: Restrict filetypes that can be uploaded

- cityinfra/templates/admin/base.html
- cityinfra/templates/admin/login.html
* only for finnish and swedish
Refs: LIIK-433
> feat: Add links to privacy policies

- cityinfra/templates/admin/base.html
- cityinfra/templates/admin/login.html
* Better capitalization of the english link in login page
* Move data protection policy link to the second last in admin page header section
Refs: LIIK-433
> fix: data protection policy link finetuning

- cityinfra/settings.py
- poetry.lock
- pyproject.toml
- traffic_control/tests/test_base_api.py
- traffic_control/tests/test_base_api_3d.py
- traffic_control/tests/test_portal_type_api.py
- traffic_control/tests/utils.py
* take django-axes into use for limiting loging attemps
Refs: LIIK-643
> feat: limit unsuccessful login attemps

- cityinfra/templates/admin/login.html
> fix: english link pointed to swedish pdf file instead of finnish

- traffic_control/tests/wfs/test_mount_wfs.py
- traffic_control/views/wfs/__init__.py
- traffic_control/views/wfs/mount.py
- traffic_control/views/wfs/views.py
> feat: Add MountReal and MountPlans to WFS API

- city_furniture/views/wfs/furniture_signpost.py
- traffic_control/views/wfs/additional_sign.py
- traffic_control/views/wfs/common.py
- traffic_control/views/wfs/mount.py
- traffic_control/views/wfs/traffic_sign.py
- traffic_control/views/wfs/utils.py
* New fields also added
Refs: LIIK-678
> feat: show enum name instead of value in WFS API

- traffic_control/resources/mount.py
> fix: base information was not taken into export nor in the template

- city_furniture/admin/furniture_signpost.py
- city_furniture/forms.py
- locale/fi/LC_MESSAGES/django.po
- locale/sv/LC_MESSAGES/django.po
- traffic_control/admin/additional_sign.py
- traffic_control/admin/affect_area.py
- traffic_control/admin/barrier.py
- traffic_control/admin/mount.py
- traffic_control/admin/operational_area.py
- traffic_control/admin/plan.py
- traffic_control/admin/road_marking.py
- traffic_control/admin/signpost.py
- traffic_control/admin/traffic_light.py
- traffic_control/admin/traffic_sign.py
- traffic_control/forms.py
- traffic_control/geometry_utils.py
- traffic_control/mixins/admin.py
- traffic_control/tests/test_forms.py
- traffic_control/tests/test_geom_utils.py
- traffic_control/tests/test_plan_admin.py
* Some restrictions are for locations that are GeometryCollections: - these is due to limitations or bugs(?) in the widget itself with 3d ge - a collection can be created using the map but modification is prohibited
* default map zoom changed to 12.5
* default location set to Helsinki railway station.
Refs: LIIK-626, LIIK-687
> feat: Use map widget for all models that have a location

- cityinfra/settings.py
- traffic_control/tests/test_import_export/test_signpost_import_export.py
> feat: Allowed location is now bound with Helsinki city limits

- traffic_control/tests/wfs/test_mount_wfs.py
- traffic_control/tests/wfs/wfs_utils.py
- traffic_control/views/wfs/utils.py
> fix: xy coordinate swap now done for all geometry types for WFS gml api

- traffic_control/enums.py
- traffic_control/static/traffic_control/openapi/openapi.yaml
> fix: Use same values for lane_number as digiroad

- cityinfra/drf_utils.py
- cityinfra/settings.py
- locale/fi/LC_MESSAGES/django.po
- locale/sv/LC_MESSAGES/django.po
- traffic_control/static/traffic_control/openapi/openapi.yaml
> feat: API maximum result per page configuration

- city_furniture/admin/common.py
- city_furniture/admin/furniture_signpost.py
- traffic_control/admin/additional_sign.py
- traffic_control/admin/affect_area.py
- traffic_control/admin/barrier.py
- traffic_control/admin/mount.py
- traffic_control/admin/operational_area.py
- traffic_control/admin/owner.py
- traffic_control/admin/plan.py
- traffic_control/admin/responsible_entity.py
- traffic_control/admin/road_marking.py
- traffic_control/admin/signpost.py
- traffic_control/admin/traffic_light.py
- traffic_control/admin/traffic_sign.py
* AdminModels that do not show uuid as a column in list page are left out
Refs: LIIK-717
> feat: Add id field to most Admin model search fields

- locale/fi/LC_MESSAGES/django.po
- locale/sv/LC_MESSAGES/django.po
- traffic_control/views/wfs/plan.py
* Finnish translation included, swedish not
Refs: LIIK-725
> feat: Change Plan WFS title to Traffic Control Plan

- traffic_control/admin/plan.py
> feat: Add name field to Plan admin search

- traffic_control/analyze_utils/plan_to_real_mapping.py
- traffic_control/db_utils.py
- traffic_control/tests/factories.py
- traffic_control/tests/test_plan_to_real_mapping.py
* TrafficSignReal with TrafficSignPlans, MountReals with MountPlans, AdditionSignReals with AdditionalSignPlans.
* Does not find matches for all, as it was kinda expected. Many plan instances are missing from database, some are too old.
* Basically only the low hanging fruits are found for now.
* No management command yet, maybe in the future when we know more about how to do the mappings.
Refs: LIIK-700
> Find and update planinstances to real models

- map-view/src/components/FeatureInfo.tsx
- map-view/src/components/LayerSwitcher.tsx
- map-view/src/locale/en.json
- map-view/src/locale/fi.json
> feat: Add some new translation to mapview

- traffic_control/forms.py
- traffic_control/tests/test_base_api.py
- traffic_control/tests/test_plan_admin.py
- traffic_control/validators.py
* instead of 500 error now a validation error is shown in the admin forms.
Refs: LIIK-751
> fix: Validator for location_ewkt form field.

- locale/fi/LC_MESSAGES/django.po
- locale/sv/LC_MESSAGES/django.po
> feat: Update missing (mostly swedish) translations

- poetry.lock
- pyproject.toml
* django-helusers 0.13.3 includes fix for the logout, nothing else needed
Refs: LIIK-615
> fix: Update django-helusers version

- map-view/src/components/FeatureInfo.tsx
> fix: Mapview crash when feature has content_s

- poetry.lock
- pyproject.toml
- traffic_control/admin/plan.py
- traffic_control/mixins/admin.py
- traffic_control/tests/test_plan_admin.py
* https://github.com/TrangPham/django-admin-confirm/issues/32 is now released so our own modifications can be removed.
Refs: LIIK-747
> feat: update django-admin-confirmation

- map-view/src/App.tsx
- map-view/src/common/Map.ts
- map-view/src/components/LayerSwitcher.tsx
* rename extravectorlayer more appropiately, and do not use that when finding features with mouseclick.
Refs: LIIK-771
> fix: Do not use plan real difference features for featureinfo popup

- map-view/src/common/MapUtils.ts
> feat: use black as area border stroke color

- map-view/src/App.tsx
- map-view/src/common/Map.ts
- map-view/src/common/MapUtils.ts
- map-view/src/components/FeatureInfo.test.tsx
- map-view/src/components/FeatureInfo.tsx
> feat: Highlight selected feature in map-view

- map-view/src/common/Map.ts
> fix: Disabling layer with no real-plan mapping

- uwsgi/docker.ini
> fix: add py-call-uwsgi-fork-hooks = true to uwsgi start parameters
