City-of-Helsinki/city-infrastructure-platform

city-infrastructure-platform/settings.py

Remove redundant STATICFILES_DIRS so that _ manage.py collectstatic_ works also without static-folder.

Remove redundant STATICFILES_DIRS.

---

traffic_control/permissions.py
traffic_control/tests/test_permissions.py
traffic_control/tests/test_portal_type_api.py
traffic_control/tests/test_traffic_sign_code_api.py
traffic_control/views.py

- Permission class to allow editing for admins, but only read access for others
- Add that permission class to portal types and traffic sign codes views
- Tests
- Test naming refactoring
Refs: LIIK-60

Add IsAdminOrReadOnly permission

---

.env.example
azure_client_ip/apps.py
azure_client_ip/middleware.py
azure_client_ip/test_middleware.py
city-infrastructure-platform/settings.py

Django-auditlog was causing issues with Azure environment. Problem was
that Azure reverse proxy forwards the end-users ip to HTTP_X_CLIENT_IP
request header, but Django-auditlog is expecting it to be in
HTTP_X_FORWARDED_FOR. We decided to create middleware to solve this
problem.
Simply put create middleware that inserts data from HTTP_X_CLIENT_IP to
HTTP_X_FORWARDED_FOR. We only want to use this middleware in Azure
environment, so initializing will raise MiddlewareNotUsed if
AZURE_DEPLOYMENT setting if False.
Refs: LIIK-62

Create middleware to fix Azure problem

---

.env.example
city-infrastructure-platform/settings.py
city-infrastructure-platform/urls.py
city-infrastructure-platform/utils.py
requirements.txt
setup.cfg

Raven is currently phasing out in favor of Sentry SDK, which also
supports newest versions of Python and Django. Our project will be
updated to Django 3 later, so we want to use packages that support
that.
- Remove Raven
- Add Sentry SDK
- Configure Sentry SDK in settings
- Add debug path for sentry
Refs: LIIK-54

Sentry integration

---

city-infrastructure-platform/urls.py

Uploaded media files were not working correctly, and we noticed that
document root for media was defined as a MEDIA_URL and not MEDIA_ROOT
as it should.
Refs: LIIK-56

Change static document root to MEDIA_ROOT

---

traffic_control/admin.py
traffic_control/forms.py
traffic_control/locale/fi/LC_MESSAGES/django.po
traffic_control/mixins.py
traffic_control/tests/test_admin.py
traffic_control/tests/test_forms.py

Using a 2d map for xy coordinates editing and a float field for z coordinate editing.
We need to specify the list of fields in order to group the xy coordinate and z
coordinate field together.
Refs: LIIK-77

Enable 3d Point editing for TrafficSignPlan and TrafficeSignReal admins

---

traffic_control/management/commands/link_additional_traffic_signs.py
traffic_control/tests/management/commands/test_link_additional_traffic_signs.py

There is no clear specification on how the additional traffic signs can be linked
to main traffic signs. So we have to come up with a solution with our own observation
with the data. This commit implement a solution can be described as follows:
1. Find all traffic signs with the type that starts with number 8. It seems Finnish
Transport Infrastructure Agency follows certain patterns to codify the traffic signs.
And additional traffic signs are all starts with 8, see details:
https://vayla.fi/web/en/road-network/traffic-signs/additional-panels
2. Find other traffic signs that are close the additional traffic signs (less
than 1m or maybe even less) on the plane (only check the x,y coordinates)
3. There might be multiple other traffic signs close by, if that's the case
we select the one that …

Add management command to link additional traffic signs to main traffic signs

---

docker-entrypoint.sh

Due to some unknown reason, Django's compilemessages get stuck in the middle of the process in the Azure QA-environment.
In order to narrow down message compilations, compile only the `traffic_control` module (other modules do not need explicit compilations for now).
Refs #LIIK-74

Simplify Django compilemessages

---

traffic_control/forms.py

The problem was that the z_coord key may not exist when form clean get called.
Refs: LIIK-83

Fix admin raising KeyError when z_coord is not filled

---

traffic_control/admin.py
traffic_control/mixins.py
traffic_control/tests/test_admin.py

Mark these fields as readonly in Admin UI and auto save the logged in user to the fields.
Refs: LIIK-84

Auto save created_by and updated_by when saving objects in Admin UI

---

traffic_control/admin.py
traffic_control/mixins/admin.py
traffic_control/mixins/api.py
traffic_control/mixins/models.py
traffic_control/models/barrier.py
traffic_control/models/mount.py
traffic_control/models/road_marking.py
traffic_control/models/signpost.py
traffic_control/models/traffic_light.py
traffic_control/models/traffic_sign.py
traffic_control/models/utils.py
traffic_control/tests/test_admin.py

This PR implements the bulk soft delete for soft delete enabled model admins. The audit log relies on signals to create log entries, and thus we cannot use the bulk operations on queryset to do the soft delete because the bulk operation does not trigger the signals. So we have to soft delete objects in queryset one by one in order to trigger the signals and create audit logs.
Note that since we are doing soft delete, the action appeared in log entry is an "update" action instead of a "delete" action.
Refs: LIIK-85

Enable bulk soft delete in Admin UI

---

traffic_control/models/traffic_sign.py
traffic_control/tests/models/test_traffic_sign.py

The bulk delete action in Admin UI is changed to use the soft_delete model method. See details: https://github.com/City-of-Helsinki/city-infrastructure-platform/pull/56
Refs: LIIK-95

Soft delete main traffic sign also soft delete associated additional signs

---

traffic_control/utils/send_traffic_sign_reals_vaisala.py

This PR changes Vaisala traffic signs import to use 0.0 as Z-value for all data.
Refs #LIIK-92

Use 0.0 as Z-value in Vaisala data import

---

traffic_control/management/commands/generate_mount_real_objects.py
traffic_control/tests/management/commands/test_generate_mount_real_objects.py

Nearby main traffic signs with same mount type  are likely to
have the same mount object. This commit enhances the generate_mount_real_objects
management command with the logic to re-use existing nearby mount real objects
when creating mount real for traffic sign real objects.
Refs: LIIK-97

Use same mount real objects for nearby traffic signs with same mount type

---

traffic_control/admin.py
traffic_control/models/mount.py
traffic_control/models/utils.py
traffic_control/serializers.py
traffic_control/tests/models/test_mount.py

This PR added an ordered list of traffic signs to both MountReal Admin UI and API end point. The traffic sign real objects mounted to the same mount real object are ordered by z coordinates in a descending order.
Refs: LIIK-73

Add ordered traffic signs to MountReal Admin UI and REST API

---

traffic_control/admin.py
traffic_control/locale/fi/LC_MESSAGES/django.po
traffic_control/utils/send_traffic_sign_reals_blom_kartta.py
traffic_control/utils/send_traffic_sign_reals_vaisala.py

This PR fixes the following issues:
- Explicitly send "is_active" flag in Traffic Sign imports.
- Force Z-coordinate to 0
- Add "source_id" and "source_name" to admin search fields
- Update translations
Refs #LIIK-104

Traffic Sign import updates

---

traffic_control/serializers.py
traffic_control/utils/send_traffic_sign_reals_blom_kartta.py
traffic_control/utils/send_traffic_sign_reals_vaisala.py

Exclude "is_active", "deleted_by", "deleted_at" from soft-delete endpoints.
Also update traffic_sign_real imports accordingly.
Refs #LIIK-105

Exclude soft-delete attributes from REST API

---

city-infrastructure-platform/settings.py

Use env to control USE_X_FORWARDED_HOST.
This is needed for proxy to show hostname correctly.
Refs #LIIK-117

Use env to control USE_X_FORWARDED_HOST

---

city-infrastructure-platform/urls.py
traffic_control/tests/test_api_file_upload.py
traffic_control/tests/test_barrier_api.py
traffic_control/tests/test_mount_api.py
traffic_control/tests/test_portal_type_api.py
traffic_control/tests/test_road_marking_api.py
traffic_control/tests/test_signpost_api.py
traffic_control/tests/test_traffic_light_api.py
traffic_control/tests/test_traffic_sign_api.py
traffic_control/tests/test_traffic_sign_code_api.py
traffic_control/utils/send_portal_types.py
traffic_control/utils/send_traffic_sign_codes.py
traffic_control/utils/send_traffic_sign_reals_blom_kartta.py
traffic_control/utils/send_traffic_sign_reals_vaisala.py

Change the api url from "/api" to "/v1" and change the api URL namespace
from "api" to "v1". Reflect this change anywhere where the url or
namespace is referenced.
Other Helsinki project API's follow this pattern so implement it for
this project as well.
Refs LIIK-122

Namespace and URL version the API

---

city-infrastructure-platform/settings.py
traffic_control/tests/factories.py
traffic_control/tests/test_pagination.py

Limit-offset pagination is more flexible pagination style that suits
the API better.
Add simple regression test so the pagination is not broken by accident
in future updates.
Refs LIIK-124

Switch to limit-offset pagination

---

traffic_control/serializers.py

Traffic sign GeoJSON serializers had affect_area set to required
implicitly through the GeometryField defaults. Explicitly define the
field as not required as it is meant to be.
Refs LIIK-138

Set affect_area to not required for geojson format

---

docker-entrypoint.sh

Azure App Service workaround in docker-entrypoint.sh was missing the ending asterisk in glob match. Thus it did not work.

Add missing asterisk to Azure workaround glob

---

uwsgi_docker.ini

Increase uWSGI buffer-size to 32k, since by default it is only 4k and not enough for our usage.
Refs LIIK-153

Increase uWSGI buffer-size

---

users/tests/test_utils.py
users/utils.py

Traffic control model instances require a created_by user. This util method
provides a inactive and non-staff user to fill the field when importing data
from data files.
no refs

Add a utils method to get system user for importers

---

traffic_control/serializers.py

TrafficControlDeviceType legacy_code and legacy_descrpition should not
be accessible through the API so exclude them from the serializer
class.
Refs LIIK-154

Hide device type legacy attributes from API

---

traffic_control/management/commands/generate_mount_real_objects.py

The additional signs (legacy code starts with "8") are now stored in
separate model AdditionalSignReal, so there is no need to the exclude
any more.
Refs: LIIK-142

Remove legacy_code exclude for main traffic signs

---

.env.example
.gitignore
docker-compose.yml
requirements.txt

Use .env-file instead of explicit environment variables.
Do not use editable version of django-helusers.
Update Docker Compose version.
Update .gitignore and .env.example settings.
Refs LIIK-157

Update docker-compose to use .env-file

---

traffic_control/serializers.py

legacy_code should not have been exposed in the API in the first place.
The value is used only for imports and it should be of no interest for
end users.

Exclude legacy_code from AdditionalSignReal API

---

traffic_control/admin/additional_sign.py
traffic_control/admin/traffic_sign.py
traffic_control/locale/fi/LC_MESSAGES/django.po
traffic_control/mixins/admin.py
traffic_control/tests/test_admin.py

Previously Django admin was set to soft delete model instances if the
model was a soft deletable model. This was to be reverted because it
was thought that model instances should be deletable for real in django
admin. The API is still only able to soft delete.
However it should still be possible to do soft delete via Django admin.
Implement changelist actions to retain that feature with minimal effort.
Also implement a soft delete list filter that allows to list all soft
deleted instances and possibly recover them if necessary. Soft deleted
instances are hidden by default.
Refs LIIK-147

Feature: Enable hard delete in django admin

---

CHANGELOG.md
traffic_control/filters.py
traffic_control/locale/fi/LC_MESSAGES/django.po
traffic_control/models/common.py
traffic_control/schema.py
traffic_control/serializers.py
traffic_control/tests/models/test_traffic_control_device_type.py
traffic_control/tests/test_traffic_control_device_type_api.py

Add `traffic_sign_type` property for `TrafficControlDeviceType` model
and expose it in API as object containing the type code and text
representation. This is done so the API endpoint results can be
filtered by the traffic sign type.
Refs LIIK-135

Add traffic_sign_type for TrafficControlDeviceType

---

traffic_control/serializers.py
traffic_control/tests/test_traffic_control_device_type_api.py

Previously the validate_target_model method is validating the target model even
when creating new device types. This cause the method fail as the device type
instance does not exist when running the validation method.
Refs: LIIK-162

Validate target model change when update target model of an exisint device type

---

traffic_control/management/commands/import_traffic_sign_reals_blom_kartta.py
traffic_control/tests/management/commands/test_imoprt_traffic_sign_reals_blom_kartta.py

The tests were missing for blom kartta traffic sign importer. This commit
added the tests to assert the importer behavior.
Aslo the general purpose Exception is replaced with CommandError in the
importer.
Refs: LIIK-159

Add tests for blom kartta traffic sign importer

---

CHANGELOG.md
city-infrastructure-platform/settings.py

Enable standard DRF TokenAuthentication mechanism.
Tokens can be created for existing users through Django Admin UI.
Refs LIIK-171

Allow users to authenticate to REST API with Token

---

CHANGELOG.md
city-infrastructure-platform/urls.py
traffic_control/serializers.py
traffic_control/tests/test_operational_area_api.py
traffic_control/views/operational_area.py

Operational areas are used to restrict the access to features, thus
they are only accessible by admin users.
Refs: LIIK-119

Add Operational Area REST API endpoint

---

CHANGELOG.md
map/static/map/app.js
map/static/map/style.css
map/templates/map/map_view.html

The features information are fetched via WMS GetFeatureInfo requests.
For simplicity purposes, we made following assumptions to the format
of WMS GetFeatureInfo responses for all layers (base on current
GeoServer setup):
- All layers are traffic control layers
- The "id" field of features are in the format of "<feature_type>.<instance_id>"
- The <feature_type> must match the model contenttype name after removing all "_"
Refs: LIIK-78

Show links to admin change view when clicking features on map view

---

CHANGELOG.md
traffic_control/admin/barrier.py
traffic_control/admin/mount.py
traffic_control/admin/road_marking.py
traffic_control/admin/signpost.py
traffic_control/admin/traffic_light.py
traffic_control/admin/traffic_sign.py
traffic_control/forms.py
traffic_control/templates/admin/traffic_control/widgets/clearable_file_input.html

Implement custom `AdminFileWidget` that adds `target="_blank"` attribute
for the `a` tag. Otherwise the template is identical with the template
used by the default widget.
Use the custom `AdminFileWidget` in file model inlines for any plan and
real models.
Refs LIIK-176

Open attached files in new tab

---

CHANGELOG.md
traffic_control/admin/additional_sign.py
traffic_control/admin/barrier.py
traffic_control/admin/mount.py
traffic_control/admin/road_marking.py
traffic_control/admin/signpost.py
traffic_control/admin/traffic_light.py
traffic_control/admin/traffic_sign.py

Admin add/change views get really slow when there's a foreign key
relation with lot of choices (20k+ in this case). To remedy this change
admin to use raw_id_fields for any relation to any traffic control real
or plan models since all of those will most likely end up having so many
choices that it will affect the usability considerably.
Refs LIIK-177

Use raw_id_fields in admin for plan and real relations

---

CHANGELOG.md

Unreleased changes were incorrectly added under v1.1.0 when those should
have been listed as unreleased. Move entries that are not released from
v1.1.0 to unreleased to fix this error.

List unreleased changes under correct title in changelog

---

traffic_control/management/commands/import_parking_areas_hki_wfs.py
traffic_control/tests/management/commands/test_import_operational_areas_hki_wfs.py
traffic_control/tests/management/commands/test_import_parking_areas_hki_wfs.py
traffic_control/tests/management/commands/utils.py

This PR adds a management command that can import parking areas from `Pysakointipaikat_alue` WFS layer . The command is idempotent and can be used to update parking areas if there're updates on WFS layer. However, it does not remove parking areas from database if there are parking areas removed from WFS layer.
It should be noted that there are mixed geometries (Polygon & MultiPolygon) in `Pysakointipaikat_alue` WFS layer. We convert all polygons to multi-polygons so that we can have a single geometry type for Parking areas.
This PR also refactor the DataSource mocking that is used both in `test_import_parking_areas_hki_wfs` and `test_import_operational_areas_hki_wfs` to remove code duplication.
Refs: LIIK-193

Add a management command to import parking areas from Helsinki City WFS layer

---

map-view/package.json
map-view/src/components/FeatureInfo.tsx
map-view/src/i18n.ts
map-view/src/index.tsx
map-view/src/locale/en.json
map-view/src/locale/fi.json
map-view/yarn.lock

This PR introduced localizations to the map view using i18next and react-i18next. The active language are detected from the url path. And the translations are stored in `map-view/src/locale/` folder.
Refs: LIIK-202

Add localization to map view

---

CHANGELOG.md
traffic_control/serializers/plan.py
traffic_control/tests/test_plan_api.py

Curently there's no easy way to configure different schema for read and write APIs, see details: https://github.com/axnsan12/drf-yasg/issues/70
We mark the linked_objects as read-only to make it more obvious in API docs.
Refs: LIIK-213

Set Plan linked_objects read only

---

CHANGELOG.md
map-view/src/common/Map.ts
map-view/src/components/FeatureInfo.test.tsx
map-view/src/components/FeatureInfo.tsx
map-view/src/locale/en.json
map-view/src/locale/fi.json
map-view/src/models.ts

Include more description to the feature in the feature info window (see screenshot), and add localization for field labels
The `value` are not displayed if the traffic sign real instance has an empty value for the `value` field
Refs: LIIK-208

Improve feature info window to include more information

---

CHANGELOG.md
traffic_control/management/commands/import_coverage_areas_hki_wfs.py
traffic_control/management/commands/import_operational_areas_hki_wfs.py

We have changed geometry fields to 3d, and source data
from HKI WFS are using 2d geometries. Force 3d coordinates
on those geometries before saving to database.
Refs: LIIK-222

 Force 3d geometry when importing from HKI WFS

---

CHANGELOG.md
traffic_control/mixins/models.py
traffic_control/models/signpost.py
traffic_control/models/traffic_sign.py
traffic_control/tests/factories.py
traffic_control/tests/test_signpost_api.py
traffic_control/tests/test_traffic_sign_api.py

This PR adds a mixin class that will use the value from related device type when saving traffic signs and signpost instances. It will only assign the value when the value is empty and there's one available from related device type.
Refs: LIIK-216

Use value from related device type when saving traffic sign/signpost instances

---

CHANGELOG.md
traffic_control/forms.py
traffic_control/static/traffic_control/css/traffic_sign_icon_select.css
traffic_control/templates/admin/traffic_control/widgets/traffic_sign_icon_select.html

Previously the widget is using the `code` field to construct the icon path for traffic signs, which is not always correct. We now have a new icon field which specifies the right svg file to use for each device type. This PR changes to use the icon field to construct the icon path for the widget.
Since there's case inconsistency between the svg file names and the ones specified in icon field, we changed the svg file names to uppercase and also convert the icon field value into uppercase when using it in the code.
Refs: LIIK-219

Improve AdminTrafficSignIconSelectWidget

---

.github/workflows/python-app.yml

This is still missing Node-side on the tests. But let's have pytest running again.

Minimal GHA pipeline for running linters & pytest

---

Dockerfile
pyproject.toml

Do installations and possible deletions in a single RUN command. This way that layers don't get too large in size.
However, we could (should) make such multi-stage Dockerfile where the production image is built on top of slim Python. It should contain only build artifacts (and runtime libs), no build-time stuff at all.
Refs LIIK-298

Improve Dockerfile

---

city_furniture/admin/furniture_signpost.py
city_furniture/management/commands/import_furniture_signpost_reals_kantakaupunki.py
city_furniture/models/common.py
city_furniture/resources/furniture_signpost.py

- Make management command importer more sturdy
- Remove unused fields from FurnitureSignpost import/export resources
- Add `__str__` methods for `CityFurnitureTarget` and `ResponsibleEntity`
- Add missing fields to Furniture Signpost Admin forms

Importer and CityFurniture changes

---

Dockerfile
apply-migrations.sh
check-migrations.sh
docker-entrypoint.sh

Add `check-migrations.sh` and `apply-migrations.sh` scripts which hold
required commands. In OpenShift we will have `job`'s which run these
separately before starting API service pod(s). Pods only check that
migrations are applied before startup.

Don't apply migrations in production image

---

city-infrastructure-platform/urls.py
map/models.py
map/views.py
traffic_control/models/affect_area.py
traffic_control/tests/factories.py
traffic_control/tests/models/test_mount.py
traffic_control/tests/models/test_traffic_control_device_type.py

We should update hel-users to fix warnings coming from there
```
.../site-packages/helusers/apps.py:8
/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/helusers/apps.py:8: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
verbose_name = _("Helsinki Users")
...
```

Fix deprecation warnings coming from Cityinfra code base

---

.gitignore
city_furniture/serializers/furniture_signpost.py
traffic_control/serializers/additional_sign.py
traffic_control/serializers/barrier.py
traffic_control/serializers/common.py
traffic_control/serializers/mount.py
traffic_control/serializers/plan.py
traffic_control/serializers/road_marking.py
traffic_control/serializers/signpost.py
traffic_control/serializers/traffic_light.py
traffic_control/serializers/traffic_sign.py
traffic_control/tests/test_additional_sign_plan_api.py
traffic_control/tests/test_additional_sign_real_api.py
traffic_control/tests/test_anonymous_requests.py

Hide created_by, updated_by and deleted_by from non-logged in users for data privacy, even when user ids are just UUID values.
Refs LIIK-367

Hide user ids from object in anonymous requests

---

traffic_control/forms.py
traffic_control/static/traffic_control/js/traffic_sign_icon_select.js
traffic_control/templates/admin/traffic_control/widgets/traffic_sign_icon_select.html

It expected icon name being like "name.svg" or "some.name.svg"
Refs LIIK-385

Fix backend error if traffic sign icon name has no dots

---

Dockerfile
uwsgi_docker.ini

To reduce noise in logs, we suppress /healthz and /readiness requests.
Install pcre library to support uWSGI internal routing, which is required by route rules to ignore specific logging.

Don't log readiness and health checks

---

traffic_control/tests/wfs/test_common_wfs.py
traffic_control/tests/wfs/wfs_utils.py
traffic_control/views/wfs/common.py
traffic_control/views/wfs/utils.py

Fix missing use of `SwapBoundingBoxMixin` hack. Also fix it's `get_query` method's logics how it uses CRS in query parameters.
Add test cases to ensure WFS working with bounding box filtering.
Refs LIIK-472

Use bounding box coordinate swapping functionality

---

.github/workflows/python-app.yml

Coverage analysis requires coverage files to be generated in pipeline.
Most Sonar configuration is defined in SonarCloud.
Refs LIIK-499

Trigger SonarCloud scan from GitHub Actions pipeline

---

poetry.lock
pyproject.toml
traffic_control/admin/utils.py

Version 3 adds support for multiple resource classes, which is what Cityinfra supports, but little differently. Instead of refactoring import/export functionality, here we just modify export so that things work as it worked before library update.

Bump `django-import-export` to 3.2.0

---

city_furniture/resources/furniture_signpost.py
city_furniture/tests/factories.py
city_furniture/tests/test_furniture_signpost_import_export.py
traffic_control/resources/additional_sign.py
traffic_control/resources/common.py
traffic_control/resources/signpost.py
traffic_control/tests/factories.py
traffic_control/tests/import_export/test_common.py
traffic_control/tests/import_export/test_signpost_import_export.py

When importing devices with child devices (i.e. signposts and furniture
signposts) a user can use non-UUID values in `id` and `parent__id`
columns to define parent-child relationships. Non-UUID values are
replaced with valid UUIDs.
Also when exporting device plans as reals template, `id` and
`parent__id` columns are prefilled with replacement values where needed.
Refs LIIK-493

Support importing parent and child devices in same Excel/CSV file

---

locale/fi/LC_MESSAGES/django.po
traffic_control/tests/test_embed.py
traffic_control/views/embed.py

Django's `XFrameOptionsMiddleware` adds `x-frame-options: DENY` to all
HTTP request headers by default. We must set an exception for embedded
views.
Add simple 404 for embedded views.
With current settings, Django's default 404 page has
`x-frame-options: DENY`, so it's not handy for embedded views. But also
it's not explaining a user _what_ was not found.

Allow embed views to be embedded in <iframe> 

---

city_furniture/admin/__init__.py
city_furniture/models/__init__.py
city_furniture/resources/__init__.py
city_furniture/tests/factories.py
city_furniture/tests/test_furniture_signpost_api.py
city_furniture/tests/test_furniture_signpost_import_export.py
city_furniture/views/wfs/__init__.py
locale/fi/LC_MESSAGES/django.po
pyproject.toml
traffic_control/admin/__init__.py
traffic_control/admin/additional_sign.py
traffic_control/models/__init__.py
traffic_control/resources/__init__.py
traffic_control/resources/common.py
traffic_control/resources/mount.py
traffic_control/tests/factories.py
traffic_control/tests/import_export/test_device_responsible_entity_import_export.py
traffic_control/tests/import_export/test_mount_import_export.py
traffic_control/tests/test_responsible_entity_api.py
traffic_control/tests/test_responsible_entity_api_permission.py
traffic_control/views/wfs/__init__.py
users/models.py

It was possible for a user to move a device from another responsible
entity to theirs, so that user could "take over" devices.
Add several tests for device import related to
responsible entity permissions for different devices.
Refs LIIK-531

Improve device import permissions with responsible entity

---

docker-entrypoint.sh
uwsgi/docker.ini
uwsgi/donotlog-health.ini

By default we suppress the probe requests logging. Set env variable `UWSGI_LOG_HEALTHZ=1` to ignore suppression.

Configurable health check log suppression

---

traffic_control/schema.py
traffic_control/tests/test_schema.py

Enums in `openapi.yaml` were not sorted as expected before. This change sorts them in the order that they appear in their enum class definition.

Sort enum value choices in OpenAPI schema

---

traffic_control/models/plan.py
traffic_control/tests/models/test_plan.py

`location_polygons` (`MultiPolygon`) cannot be created if any related device location's buffered geometry is a multipolygon. Taking `.convex_hull` ensures that the geometry is a polygon.
Refs: LIIK-568

Ensure device geometries to be polygons when deriving Plan location

---

poetry.lock
pyproject.toml

`pep8-naming` is `flake8` plugin, but `flake8` was recently replaced with `ruff`.

Remove `pep8-naming` from dev dependencies

---

traffic_control/admin/barrier.py
traffic_control/admin/mount.py
traffic_control/tests/test_source_name_source_id_api.py

Barriers and mounts were missing source name and id from their admin view.

Add source name and source ID to missing admin views

---

cityinfra/settings.py

* BrowsableAPIRenderer causes over 1000 db hits, because it populates selection lists for many objects
* As it is not needed better just to remove it totally
*  instead of making alot of selected related statements
Refs: LIIK-602

fix: Allow only JSONRenderer as DRF default renderer

---

traffic_control/forms.py
traffic_control/geometry_utils.py
traffic_control/tests/test_additional_sign_admin.py
traffic_control/tests/test_plan_admin.py

* initial z coordinate value get for GeometryCollections.
* Fixed changing other fields than location fixed, this was due to differently rounded values from mapwidget in each run.
* Creating objects with only location_ewkt field is now working
* No more additional logentries, this also happened due to mapwidget coordinate rounding
* Fixed 500 Error when creating objects where location field is not mandatory
Refs: LIIK-705

fix: Many fixes related to location handling in admin forms

---

locale/fi/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/django.po
traffic_control/views/wfs/mount.py

* Finnish and swedish translation also added
Refs: LIIK-710

fix: Add missing internationalization support for mount centroid titles

---

users/models.py
users/tests/test_user_model.py

feat: Register User model to auditlog

---

traffic_control/resources/device_type.py
traffic_control/tests/test_import_export/test_device_type_import_export.py

* code field still remains as the key field.
* id field is not used when importing, it is there in the export file just to give more information
Refs: LIIK-684

feat: Add id field to TrafficControlDeviceType export file

---

map-view/src/components/FeatureInfo.tsx
map-view/src/locale/en.json
map-view/src/locale/fi.json
map-view/src/models.ts
traffic_control/tests/wfs/test_mount_wfs.py
traffic_control/views/wfs/common.py
traffic_control/views/wfs/mount.py

* OpenLayers map supports only Point geometries
Refs: LIIK-698

feat: centroid location rendering to WFS json output

---

traffic_control/admin/plan.py

* First fix just fixed the symptom not the root cause
* Root cause was that AdminConfirmMixin.get_confirmation_fields does not return a copy of confirmation fields
* and when PlanAdmin removes "location" fields from confirmation fields once, it is never there again without taking a copy
Refs: LIIK-750

fix: Derive location confirmation not asked when it should be

---

traffic_control/models/common.py
traffic_control/tests/test_traffic_control_device_type_admin.py

fix: Show helfpul error when invalid target data model is selected

---

cityinfra/settings.py
map-view/package.json
map-view/src/App.tsx
map-view/src/api/__mocks__/mock-data.ts
map-view/src/common/AddressSearchUtils.ts
map-view/src/common/Map.ts
map-view/src/common/MapUtils.ts
map-view/src/components/AddressInput.module.css
map-view/src/components/AddressInput.tsx
map-view/src/locale/en.json
map-view/src/locale/fi.json
map-view/src/locale/sv.json
map-view/src/models.ts
map-view/yarn.lock
map/views.py

* Marker placed with the address on the map
* 3 characters needed before search is initiated, no need for debounce with the default limit of 20 results
Refs: LIIK-686

feat: Address search to map view
